import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from '../hooks/useTranslation';
const DemoEndModal = ({ onBackToMenu }) => {
    const { language } = useTranslation();
    return (_jsx("div", { className: "absolute inset-0 bg-black bg-opacity-90 backdrop-blur-md flex items-center justify-center z-[100] p-6 animate-fade-in", children: _jsxs("div", { className: "bg-gray-900 border-2 border-amber-500 rounded-lg shadow-[0_0_50px_rgba(245,158,11,0.5)] w-full max-w-2xl p-10 text-center relative overflow-hidden", children: [_jsx("div", { className: "absolute top-0 left-0 w-full h-2 bg-gradient-to-r from-transparent via-amber-500 to-transparent" }), _jsx("div", { className: "absolute bottom-0 left-0 w-full h-2 bg-gradient-to-r from-transparent via-amber-500 to-transparent" }), _jsx("h2", { className: "text-5xl font-bold font-cinzel text-amber-400 mb-6 drop-shadow-lg", children: language === 'de' ? 'Danke fürs Spielen!' : 'Thanks for playing!' }), _jsx("p", { className: "text-gray-300 text-xl mb-8 leading-relaxed font-light", children: language === 'de'
                        ? _jsxs(_Fragment, { children: ["Du hast das Ende der Demo von ", _jsx("span", { className: "font-bold text-white", children: "Movie Business" }), " erreicht. Wir hoffen, der erste Einblick in die harte, aber faszinierende Welt des Film-Business hat Dir gefallen."] })
                        : _jsxs(_Fragment, { children: ["You have reached the end of the ", _jsx("span", { className: "font-bold text-white", children: "Movie Business" }), " demo. We hope you enjoyed this first glimpse into the demanding but fascinating world of the movie business."] }) }), _jsxs("div", { className: "bg-gray-800/50 p-6 rounded-xl border border-gray-700 mb-8", children: [_jsx("p", { className: "text-lg text-gray-400 mb-2", children: language === 'de' ? 'Die Vollversion erscheint am:' : 'The full version releases on:' }), _jsx("p", { className: "text-3xl font-bold text-white tracking-widest mb-1", children: "25.02.2026" }), _jsx("p", { className: "text-sm text-cyan-400 font-bold uppercase tracking-wider", children: language === 'de' ? 'Auf Steam' : 'On Steam' })] }), _jsx("p", { className: "text-gray-400 italic mb-10", children: language === 'de'
                        ? '"Wir freuen uns darauf, Dich bald wieder als legendären Produzenten zu sehen!"'
                        : '"We look forward to seeing you again soon as a legendary producer!"' }), _jsx("button", { onClick: onBackToMenu, className: "bg-amber-600 hover:bg-amber-500 text-white text-xl font-bold py-4 px-12 rounded-sm uppercase tracking-wider transition-all shadow-lg transform hover:scale-105", children: language === 'de' ? 'Zurück zum Hauptmenü' : 'Back to Main Menu' })] }) }));
};
export default DemoEndModal;
